language: cpp
sudo: required
dist: trusty
compiler:
  - gcc
os:
  - osx
ruby: 2.2.0
before_install:
  - brew install SDL2
  - brew install SDL2_Image
before_script:
  - gem install magica
script:
  - magica run

