language: cpp
sudo: required
dist: trusty
compiler:
  - gcc
os:
  - osx
  - linux
ruby: 2.2.0
before_install:
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get update; fi
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get install libsdl2-dev libsdl2-image-dev; fi
  - if [ $TRAVIS_OS_NAME == osx ]; then brew install SDL2; fi
  - if [ $TRAVIS_OS_NAME == osx ]; then brew install SDL2_Image; fi
before_script:
  - gem install magica
script:
  - magica test

